version: "3.9"

networks:
  localdev:
    name: localdev

services:
  web:
    build: .
    restart: always
    container_name: todobernetes-web
    ports:
      - "5000:80"
    depends_on: 
      - db-server
    networks:
      - localdev

  db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: todobernetes-db
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1433
      - MSSQL_SA_PASSWORD=Str0ngP4ssw0rd?      
    ports:
      - "1433:1433"
    networks:
      - localdev